version: '2'

services:
  db:
    image: mariadb
    volumes:
      - hackathon-db:/var/lib/mysql
    ports:
      - ${DOCKER_MYSQL_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DOCKER_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DOCKER_MYSQL_DATABASE}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - ${DOCKER_PHPMYADMIN_PORT}:80
    depends_on:
      - db
    environment:
      - MYSQL_ROOT_PASSWORD=${DOCKER_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DOCKER_MYSQL_DATABASE}

  nginx:
    build: docker/nginx
    volumes_from:
      - php
    volumes:
      - ./docker/nginx/sites/laravel.conf:/etc/nginx/sites-available
    depends_on:
      - php
    labels:
      - "traefik.backend=${DOCKER_NGINX_HOST}-nginx"
      - "traefik.frontend.rule=Host:${DOCKER_NGINX_HOST}"
      - "traefik.port=80"
    environment:
      - VIRTUAL_HOST=${DOCKER_NGINX_HOST}

  php:
    build:
      context: docker/php
      dockerfile: debian.Dockerfile
    working_dir: /var/www/html
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    environment:
      - VIRTUAL_HOST=${DOCKER_NGINX_HOST}

  redis:
    image: redis
    command: redis-server --requirepass 123456
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    restart: always
    ports:
        - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}

volumes:
  hackathon-db:

networks:
  default:
    external:
      name: reverse_proxy
